[package]
name = "libsecp256k1"
description = "Pure Rust secp256k1 implementation."
license = "Apache-2.0"
version = "0.2.3"
authors = ["Wei Tang <hi@that.world>"]
repository = "https://source.that.world/source/libsecp256k1-rs/"
keywords = [ "crypto", "ECDSA", "secp256k1", "bitcoin", "no_std" ]

[lib]
name = "secp256k1"

[dependencies]
rand = { version = "0.6", default-features = false }
hmac-drbg = "0.1"
sha2 = "0.6"
digest = "0.6"
typenum = "1.10"
arrayref = "0.3"

[dev-dependencies]
secp256k1-test = "0.7"
rand = "0.6"
clear_on_drop = "0.2.3"

[workspace]
members = [
  "./gen/ecmult",
  "./gen/genmult",
]
